### ISSUE TITLE
fractal tree: mapping angle without slider in Processing

### ISSUE THREAD

**Issue by Huhnmonster** [CodingRainbow/Rainbow-Code#33]
Hey man, 

first off, I love your videos. The way you explain things is so refreshing and it sounds like you are a human, not just someone reading of his premade script.
I hope you can help me with my problem.
I tried to replicate the fractal tree in Processing and it works out fine, except I tried to replace your slider by just mapping mouseX in the range. The problem I now have is that one fractal tree with angle x gets drawn over another fractal tree with angle x-1 for example.
I tried resetting the background but the recursiveness makes it impossible (correct me if I am wrong).

```java
void setup(){
  size(800,640);
  background(51);
}

void draw(){
  int len = 200;
  translate(width / 2, height);
  stroke(255);
  strokeWeight(2);
  branch(len);
}

float angle = PI/4;

void branch(float len){
  line(0,0,0,-len);
  if (len > 4) {
    pushMatrix();
    translate(0,-len);
    rotate(map(mouseX,0,width,0,2*PI));
    branch(len*0.67);
    popMatrix();
    pushMatrix();
    translate(0,-len);
    rotate(-map(mouseX,0,width,0,2*PI));
    branch(len*0.67);
    popMatrix();
  }
}
```

**Comment by shiffman** [comment]
You can use the `map()` function to map angle based on `mouseX`.
