### ISSUE TITLE
About Twitter Bot Tutorial and hiding config data

### ISSUE THREAD

**Issue by SetupandDraw** [CodingRainbow/Rainbow-Code#42]
Hi Dan, could you be more precise about this part? I don't understand what you mean here // Add file .gitignore: config.js

Sorry if this sounds a stupid question.

**Comment by shiffman** [comment]
`config.js` is the file where  I store my "secret" twitter authorization tokens.  I put `config.js` in `.gitignore` so that it doesn't get uploaded to github.   In my examples, you'll find `config-empty.js` which is a template for how to make your own `config.js` with your out authorization info.
