### ISSUE TITLE
Mitosis in Processing - "function copy()" does not exist.

### ISSUE THREAD

**Issue by Penguindongames** [CodingRainbow/Rainbow-Code#45]
I was very thrilled to see that there was a Processing version of the Mitosis project. I copied it down, and ran the program. There was an error. Here is what it said: "The function copy() does not exist". It said that the error was coming from this line of code: `this.pos = pos.copy();`. I don't understand the issue, but it would be nice if someone could help me out.

(Im using Processing 2.2.1, that might be an issue...)

**Comment by shiffman** [comment]
yes, for older processing try `get()` instead!
